### PR TITLE
API docs

### PR DESCRIPTION
**Pull request by ahopkins**

### CODE REVIEW

**Comment by nitishmalang** [comment]
Can I work on this

**Comment by ahopkins** [comment]
Absolutely

**Comment by ahopkins** [comment]
@nitishmalang I added some quick information here: https://github.com/ahopkins/mayim/blob/main/CONTRIBUTING.md

LMK if there is a particular section you would like to work on so that we can coordinate and not duplicate efforts. I am hoping to start by getting all of the objects exposed in `mayim.__init__` documented first. Then merge this and get incrementally work through the rest of the objects.

**Comment by ahopkins** [comment]
@nitishmalang I am going to merge this in and get a release out. Please feel free to open a new PR with more additions to API docs.

**Pull request merged**
